CFLAGS=-O -Wuninitialized -Werror -I. -I../sys -I../
CC=GCC

# all: example-codelock example-buffer example-small
all: example-yield-with-time

example-codelock: example-codelock.c hsm.c demo_process.c times.c

example-buffer: example-buffer.c

example-small: example-small.c

example-yield-with-time: example-yield-with-time.c
